apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJSRzFwZEhKcGVWSmhaRHBuYUhCZk1qRm5abGR4V25KUmFGWnlja3BMU0VoUE1tMW1hRTA1Y1RFMFRqWXlNVVprYnpGVyIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
